### ISSUE TITLE
Add concatenation of templates

### ISSUE THREAD

**Issue by sielaq** [eBayClassifiedsGroup/marathon_deploy#2]
It would be another nice feature of `default.yaml`  
(which also supports macros).
Enabled by additional option like `--concatenate`  - multiple times,
like  `--concatenate a.yaml --concatenate b.yaml` ....

It would contains common stuff for all like:

```
healthChecks:
- portIndex: 0
  protocol: TCP
  timeoutSeconds: 30
  intervalSeconds: 10
  gracePeriodSeconds: 30
  maxConsecutiveFailures: 3
- portIndex: 0
  protocol: HTTP
  timeoutSeconds: 30
  intervalSeconds: 10
  gracePeriodSeconds: 30
  maxConsecutiveFailures: 3
  path: /%%SERVICE_NAME%%/health/ping
```

and it will be concatenated with `deploy.yaml` - with smart way - if some components already exist in 
`deploy.yaml` - then cover the `default.yaml` 

Open question is how "smart" should it be in case of common components, for ex.:
`default.yaml`:

```
container:
  docker:
    network: BRIDGE
  type: DOCKER
```

`deploy.yaml`:

```
container:
  docker:
    image: foo/bar
```

A.Should whole container be replaced ?
or
B Should be merged ?

In the end it would be awesome to have concatenation with multiple yaml files
